config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "/events" => "events#index", as: :events
  # get "/events/new" => "events#new", as: :new_event
  # get "/events/:id" => "events#show", as: :event
  # get "/events/:id/edit" => "events#edit", as: :edit_event
  # patch "/events/:id" => "events#update"
  # post '/events' => "events#create"
  # delete "/events/:id" => "events#destroy", as: :destroy_event

  resources :events do
    resources :registrations
    resources :likes
  end

  resources :users
  resource :session, only: [:new, :create, :destroy]
  get "/signup" => 'users#new'

  root :to => "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event

  validates :name, :email, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
    message: "is invalid" }, uniqueness: { case_sensitive: false }

  def admin?
    self.is_admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :udpate, :destroy]
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @registrations = @user.registrations
    @events = @user.liked_events
  end

  def new
    @user = User.new
  end

  def create
  
    @user = User.new(user_params)
  
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Account has been successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Account has been successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to users_path, notice: "Account has been deleted"
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_correct_user
      unless is_currect_user?(@user)
        flash[:error] = "you are not a correct user!"
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def button_caption(user)
    user.new_record? ? 'Create Account' : 'Update Account'
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>

  <% if @user.errors.any? %>
    <div class="error">
      <h1><%= @user.errors.count %> Error has been occured </h1>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <%= f.submit button_caption(@user) %> 
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
  <div class="well">
    <%= link_to user.name, user %>
    came at <%= time_ago_in_words(user.created_at) %> ago
  </div>
<% end %>

app/views/users/new.html.erb
<h1>SignUp</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= @user.email %>

<% if @registrations.present? %>
  <h1>Registrations</h1>
  <% @registrations.each do |r| %>
    <div class="well">
      <div class="image">
        <%= image_tag r.event.image_file_name %>
      </div>
      <%= link_to r.event.name, r.event %>
      <div class="pull-right">
        <%= event_date(r.event.event_date) %>
      </div>
    </div>
  <% end %>
<% end %>


<% if @events.present? %>
  <h1>Liked Events</h1>
  <% @events.each do |event| %>
    <div class="well user_like">
      <div class="image">
        <%= image_tag event.image_file_name %>
      </div>
      <%= link_to event.name, event %>
    </div>
  <% end %>
<% end %>

<br><br>
<% if is_currect_user?(@user) %>
  <%= link_to "Edit Account", edit_user_path(@user), class: 'btn btn-primary btn-sm' %>

  <%= link_to "Delete Account", user_path(@user), method: :delete, class: 'btn btn-danger btn-sm' %>
<% end %>