config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get "/events" => "events#index", as: :events
  # get "/events/new" => "events#new", as: :new_event
  # get "/events/:id" => "events#show", as: :event
  # get "/events/:id/edit" => "events#edit", as: :edit_event
  # patch "/events/:id" => "events#update"
  # post '/events' => "events#create"
  # delete "/events/:id" => "events#destroy", as: :destroy_event

  resources :events do
    resources :registrations
    resources :likes
  end

  resources :users
  resource :session, only: [:new, :create, :destroy]
  get "/signup" => 'users#new'

  root :to => "home#index"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :events_categories, dependent: :destroy
  has_many :categories, through: :events_categories

  validates :name, :place, :event_date, :spot, :image_file_name, presence: true

  validates :spot, numericality: { only_integer: true }

  # Class method
  def self.upcoming
    where("event_date >= ?", Time.now).order('event_date')
  end

  def self.past
    where("event_date < ?", Time.now).order('event_date DESC')
  end

  def sold_out?
    availability = spot - registrations.persisted_records.size
    availability.zero? || availability < 0
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :get_event, only: [:show, :edit, :update, :destroy]
  #before_action :get_event, excpet: [:new, :create, :index]
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin_user, except: [:index, :show]

  def index
    @events = Event.upcoming
  end

  def show
    @users = @event.likers
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event), notice: 'Event has successfully updated!'
    else
      flash.now[:error] = "Some error occured!"
      render :edit
    end
  end

  def new
    @event = Event.new()
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event), notice: 'Event has successfully created!'
    else
      render :new
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: 'Event has been successfully deleted!'
  end

  private
    def get_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :price, :place, :event_date, :description, :image_file_name, :spot)
    end

    def require_admin_user
      unless admin_user?
        flash[:error] = "Only Admin user can create or udpate an event."

        redirect_to root_path
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_price(price)
    if price.blank? || price.zero?
      'Free'
    else
      number_to_currency(price, unit: 'RS ')
    end
  end

  def event_date(date)
    return date.strftime('%d/%B/%Y : %H:%M %p') if date 
    'Comming Soon'
  end

  def like_unlike_button(event)
    like = event.likes.find_by(user_id: current_user.id)
    if like
      link_to 'Unlike', event_like_path(event, like), method: :delete, class: 'btn btn-sm pull-right'
    else 
      link_to 'Like', event_likes_path(event), method: :post, class: 'btn btn-sm pull-right'
    end
  end
end

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true) do |f| %>

  <% if @event.errors.any? %>
    <div class="error">
      <h1><%= @event.errors.count %> Error has been occured </h1>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :event_date %>
    <%= f.datetime_select :event_date, {ampm: true}, { class: "form-control" } %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :spot %>
    <%= f.text_field :spot, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :image_file_name %>
    <%= f.text_field :image_file_name, class: "form-control" %>
  </div>


  <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing : `<%= @event.name %>`</h1>

<%= render 'form' %>

<%= link_to 'Cancle', event_path(@event) %>

app/views/events/index.html.erb
<h1>List Events</h1>

<%= link_to 'New', new_event_path, class: 'btn btn-primary' if admin_user? %>

<% @events.each do |event| %>
  <div class="well">
    <div class="event_image">
      <%= image_tag event.image_file_name %>
    </div>
    <div class="event_name"><%= link_to event.name, event_path(event.id) %></div>
    <div class="pull-right"><%= event_price(event.price) %></div>
    <%= event_date(event.event_date) %> at <%= event.place %><br>
     
    <span>Available : <%= pluralize(event.spot, 'Spot') %></span>
    <p><%= truncate(event.description, length: 30) %></p>

    <%= link_to 'Delete', event_path(event), method: :delete %>
    <%= link_to "Who's Registered", event_registrations_path(event) %>

    <div class="like">
      <%= event.likes.count %>
      <%= like_unlike_button(event) if current_user %>
    </div>

    
  </div>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Cancle', events_path() %>

app/views/events/show.html.erb
<div class="event_image">
  <%= image_tag @event.image_file_name %>
</div>
<div class="event_name"><%= @event.name %></div>
&nbsp;&nbsp;&nbsp;<div class="pull-right"><%= event_price(@event.price) %></div>
<%= event_date(@event.event_date) %> at <%= @event.place %><br><br>
<span>Available : <%= pluralize(@event.spot, 'Spot') %></span>
<p class="description"><%= @event.description %></p>


<div class="liked_events">
  <% if @users.present? %>
    <h1>Likers</h1>
    <ul>
      <% @users.each do |user| %>
        <li><%= link_to user.name, user %> </li>
      <% end %>
    </ul>
  <% end %>
</div>

<%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-default' %>
<%= link_to 'Delete', event_path(@event), method: :delete, class: 'btn btn-danger' %>
<%= link_to "Who's Registered", event_registrations_path(@event), class: 'btn btn-default' %>
<%= regiter_or_soldout(@event) %>